name: Build and Release Flutter APK

on:
  push:
    # Se déclenche uniquement lorsque tu pousses un tag de version (ex: v1.0.2, v2.1.0)
    tags:
      - 'v*'
  # Te permet toujours de lancer le build manuellement pour tester
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK Release
        run: |
          flutter build apk --release --dart-define=SYNC_API_BASE_URL=https://co-compagnon-sync.crame-teddy.workers.dev

      # Remplacement de l'artifact temporaire par une Release définitive
      - name: Create GitHub Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          # Spécifie le chemin de l'APK à inclure dans la Release
          files: build/app/outputs/flutter-apk/app-release.apk
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Clé secrète fournie automatiquement par GitHub